[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/public/:splat"
  status = 200

[[redirects]]
  from = "/api-mutate/*"
  to = "/.netlify/functions/mutate/:splat"
  status = 200

[[redirects]]
  from = "/api-proscore"
  to = "/.netlify/functions/proscore"
  status = 200

# Auth / profile join
[[redirects]]
  from = "/api-auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

